version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: .lazycat-build/shumai.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: shumai

build:
  run_buildscript: false

images:
  - id: shumai
    target: service
    service: shumai
    source: docker.io/shumaione/shumai
    channel: stable
    sort: semver
    tag_regex: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
    delivery:
      mode: mirror
      image_template: docker.1ms.run/shumaione/shumai:{tag}

stores:
  official:
    enabled: false
  private:
    enabled: true
    skip_if_version_exists: true
    name: Shumai
    summary: 由 GitHub Actions 自动发布