application:
  subdomain: shumai
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://shumai:3000/
services:
  postgres:
    # pgvector/pgvector:pg18
    # upstream: pgvector/pgvector:pg18
    image: docker.1ms.run/pgvector/pgvector:pg18
    binds:
      - /lzcapp/var/shumai/postgres:/var/lib/postgresql/18/docker
    environment:
      - POSTGRES_USER=shumai
      - POSTGRES_PASSWORD={{ stable_secret "postgres_password" }}
      - POSTGRES_DB=shumai_db
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U shumai -d shumai_db
      interval: 5s
      timeout: 5s
      retries: 5
  shumai:
    # shumaione/shumai:0.3.9
    # upstream: docker.io/shumaione/shumai:0.4.0
    image: docker.1ms.run/shumaione/shumai:0.4.0
    depends_on:
      - postgres
    binds:
      - /lzcapp/var/shumai/data:/app/data
    environment:
      - DATABASE_URL=postgres://shumai:{{ stable_secret "postgres_password" }}@postgres:5432/shumai_db?search_path=public&sslmode=disable
      - SHUMAI_SERVER_PORT=3000
      - STORAGE_BACKEND=local
      - AWS_ENDPOINT_URL_S3=http://localhost:3000
      - BETTER_AUTH_SECRET={{ stable_secret "better_auth_secret" }}
      - ENABLE_WEAKER_NESTED_SANDBOX=true
usage: |-
  打开后，Shumai 会自动完成数据库初始化，首次使用稍等片刻即可进入。
  所有媒体文件保存在应用数据目录中，升级应用不会丢失。
