package: community.lazycat.app.shumai
version: 0.3.11
name: Shumai
description: "AI-native, open-source Frame.io alternative for creative collaboration."
min_os_version: 1.5.0
homepage: https://github.com/shumaiOne/shumai
author: shumaiOne
permissions:
  required:
    - net.internet
locales:
  zh:
    name: Shumai
    description: "AI 原生、开源的 Frame.io 替代品，用于创意协作。"
  en:
    name: Shumai
    description: "AI-native, open-source Frame.io alternative for creative collaboration."
